# -*- coding: utf-8 -*-
"""stats-read-open-state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDNFTT3DH05ytYyJ46pHQm-Ym5NzL_Q8

# 2026-10-02

## State

The surviving position is an assumption claim about the competing design. The adjacency prior assumes spatial smoothness that heat vulnerability does not have, and the assumption fails at p99, where the estimand lives. The mechanism is now stated: Leroux precision is 1 − ρ + ρ·nᵢ, a function of border count, not of evidence, and one ρ governs every cross-basis coefficient, so the cold end and the heat end of the curve are made equally spatial with no argument. Rests on quijalzamorano2024sbdlnm, rutten2026spatialvarying, rutten2026effectmod, quick2025smallarea. Does not cover a coefficient-specific or heavy-tailed ρ.

The field sorts into a grid, one-stage or two-stage by smooth-the-coefficients or meta-predict-them. Quick, Quijal and Rutten smooth by adjacency (ICAR, Leroux, Leroux). Rutten's effect-modification paper adds a fifth cell, one named modifier inside one likelihood. Masselot, Vázquez and CanVS meta-predict in two stages. CanVS is alone in its cell only at the DA; vazquez2025norway is the same cell at the municipality and passed review. quick2025smallarea names the DA-scale national design as future work in print.

Every earlier position died the same way. Tractability closed when Rutten ran 391 municipalities in minutes; interpretability was superseded. Both were capability claims about the other camp and expired on its publication schedule. What survives is a claim about what the other design assumes.

Validation in the field is circular, and the instances are now named. masselot2025extensions scores held-out cities against BLUPs from the full model it is testing. Quijal ran no simulation study, and his only public data are draws from his own model 4. Rutten simulates θⱼ from a single-ρ Leroux process, then shows a single-ρ model recovers it. Vázquez clusters the units first and gets I² = 0 by construction. A planted truth generated outside the model is the only check in the set that does not come from the model being checked.

Every published fine-unit surface shows fixed-effect spread only. sera2019mixmeta eq 6 shrinks by Ψ̂Σ̂⁻¹, driven by first-stage variance, which is deaths. A DA has no first-stage variance, so the downscale is eq 5, ŷ₀ = X₀β̂, the ρ → 0 limit of a BLUP. Ψ never reaches the mapped unit, and covariate-homogeneous cities read as safe. Assigned to discussion and a successor paper.

The modifier question has three answers and none scales. Univariate screening, with PCA run and set aside (sera2019urban). One named modifier inside the likelihood, conceded as "computationally highly demanding" for more (rutten2026effectmod). PCA that hides drivers, conceded for the fourth time in vazquez2025norway. masselot2023cgaim is the supervised alternative, univariate outcome only. Sera names the collinearity and stops; gasparrini2022cts supplies the downscale; CanVS sits between them.

The field has no monograph. Its theory lives in tutorial papers, vignettes and stapled theses.

The grid is bookkeeping. Gasparrini pads zero-death days and shifts within unit; Éric and Lulu drop zero-event strata and join lags by date offset. The conditional likelihood gives the same coefficients either way. No paper in the set says so.

The release regime is not one regime. Three Statistics Canada documents give three answers on coefficient covariance, and the one that binds CVSD is unread. Every two-stage paper in the set pooled reduced sets outside an enclave; the Canadian enclave may not let them travel.

Recurring, and remarked on by none. The cold end is modifier-null across 340 cities (sera2019urban), inverts below −11 °C in Norway, and in Canada the heat burden sits above p90 (gasparrini2015lancet Table S3). The three Canadian anchors are each cited for something else. Sᵢ is assumed known in every second stage and never sized.

## Open

1 Which rule binds coefficient covariance for CVSD output, and does any fine-unit map in the set release anything past the surface? The November release rides on it. Decided by the DAD vetting handbook, Models p. 16, Graphs p. 18, Heat Maps p. 19. Unread.

2 Has anyone published a planted-truth check of a fine-unit surface, with the truth generated outside the model? Four papers checked, none. A kill-search unbuilt; a hit falsifies the circularity claim.

3 Does a coefficient-specific or heavy-tailed ρ exist in the adjacency camp? Rutten's BYM2 comparison was run on single-ρ truth, so it cannot answer this. A hit weakens the surviving position.

4 What window do published minimum-risk searches use, and on what argument? Éric searches p25–p90 on the BLUPs; gasparrini2015lancet takes the MMT from the BLUP with Table S1's price attached; the twin's window is unread.

5 What does treating Sᵢ as known cost at the DA, where Sᵢ does not exist? sera2019mixmeta lists five fixes from the mixed-model literature and implements none.

6 Where did p10/p75/p90 with 21 lags originate, and was it argued or inherited? Untraced.

7 Does any national surface report Ψ at the mapped unit? The State says no; unsearched as a kill-search.

8 What does Masselot's kriged residual say about meta-prediction? By his own concession a krigeable residual can come from missing key variables, which makes it a missing meta-predictor.

9 Will the Canadian cold tail invert the way Norway's does, and does the DLNM edge misbehave there? Unexamined for Canada.

10 Has any Canadian DA-level study relinked every year through one PCCF vintage and said so? Positions the linkage paragraph.

## Shelf

Gasparrini, CTS_smallarea 03.mainmod and 04.intmod — the twin's model, stratum and time term; for 4 and 6. gasparrini/Extended2stage — Masselot's code; for 8. Masselot 2025 §3.5 — the kriging step; for 8. Rutten 2026 Text S1 — the simulation code; for 3. Rutten LPS code; for 3. Quijal, three R scripts and WinBUGS code; for 3. Vázquez 2025 Methods S2 — the I² = 0 witness. clustgeo — the α-blend clustering, fallback only. dlnmTS vignette; for 6. mixmeta vignette — Ψ at the unit and the df.residual tension; for 5 and 7. Sera 2019 mixmeta eqs 5 and 6; for 7. Gasparrini 2015 Lancet, the limitations paragraph — anchor 1, for a direct quote; Tables S1, S3, S4 — for 4 and the cold tail. mmc1 S4 × sera2020airconditioning eTable 1a — anchor 2. DAD vetting handbook pp. 16, 18, 19, 42; for 1.
"""