# -*- coding: utf-8 -*-
"""stats-read-ledger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afGAs5jxqEFN6CC9qLP5jwo7pP5-cuFG

# Stats read ledger
last updated 2026-10-02

## Log

### 2026-10-02_vdl-tools-capture-shelf

thirteen tools rows into the tracker: vDL environment, Lulu's Step 1 object, mortality_cts, DA Daymet series, Éric's extraction, Éric's release script, Éric's Québec example, Lulu's pipeline, Gasparrini's tutorial, VMA manual, economic handbook, CVSD §5.4, request form. thirty-four shelf rows, seven with maps in hand (DAD handbook, Stat/Transfer, VMA, economic handbook, request form, Researcher Resources, workspace tree), the rest [COPY]. synthesis written, template inferred from the math files. literature open state and this ledger created. no vDL login

## Reflexes

- lags wanted on filtered rows → join the complete exposure table at date − k; the full grid is never needed
- one ρ across every cross-basis coefficient → cold and heat were made equally spatial; ask where that was argued
- a holdout scored against the full model's blup → the model is grading itself; not validation [masselot §4]
- I² = 0 right after a clustering step → the clustering did it, not the model [vázquez]
- a single named modifier inside the likelihood → it cannot take many; the author says so somewhere, find the line [rutten effect-mod]
- knots at each unit's own percentiles → each unit builds its own basis; no slicing a national one
- a row drafted → run the second pass before showing it; the first exists to be demolished
- a verbatim cell → raw only; what is missing goes to open items
- a source path → where the thing lives, never the document that carried it

## Notes

- put a day down to explore an environment before assuming what it lacks; five weeks went to three gates that were never doors [2026-10-02]
- reuse a template that already works before inventing one; infer it from the files that exist [2026-10-02]
- what cannot be read off one row is the only thing worth writing above the rows [2026-10-02]
"""